<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SchoolDetail;

class SchoolDetailSeeder extends Seeder
{
    public function run(): void
    {

        SchoolDetail::insert([
            [
                'name' => 'SDN 1 Kuta',
                'institutionCode' => 'INST0001',
                'schoolId' => 1,
                'statusId' => 1,
                'educationLevelId' => 1,
                'ownershipStatus' => 'Negeri',
                'dateEstablishmentDecree' => '2000-01-01',
                'operationalLicense' => 'IZIN-001',
                'dateOperationalLicense' => '2001-01-01',
                'principal' => 'Ketut Putra',
                'operator' => 'Made Dewi',
                'accreditationId' => 1,
                'curriculum' => 'K13',
                // 'telpNo' => '0361-123001',
                'tuitionFee' => 0,
                'numStudent' => 300,
                'numTeacher' => 25,
                'movie' => 'https://youtube.com/dummy1',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SMPN 2 Kuta',
                'institutionCode' => 'INST0002',
                'schoolId' => 2,
                'statusId' => 2,
                'educationLevelId' => 2,
                'ownershipStatus' => 'Swasta',
                'dateEstablishmentDecree' => '2005-02-01',
                'operationalLicense' => 'IZIN-002',
                'dateOperationalLicense' => '2006-01-01',
                'principal' => 'Ni Luh Sari',
                'operator' => 'Komang Gede',
                'accreditationId' => 2,
                'curriculum' => 'Kurikulum Merdeka',
                // 'telpNo' => '0361-123002',
                'tuitionFee' => 150000,
                'numStudent' => 400,
                'numTeacher' => 30,
                'movie' => 'https://youtube.com/dummy2',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SDN 3 Mengwi',
                'institutionCode' => 'INST0003',
                'schoolId' => 3,
                'statusId' => 1,
                'educationLevelId' => 1,
                'ownershipStatus' => 'Negeri',
                'dateEstablishmentDecree' => '2008-01-01',
                'operationalLicense' => 'IZIN-003',
                'dateOperationalLicense' => '2009-01-01',
                'principal' => 'Wayan Budiasa',
                'operator' => 'Made Santika',
                'accreditationId' => 1,
                'curriculum' => 'K13',
                // 'telpNo' => '0361-123003',
                'tuitionFee' => 0,
                'numStudent' => 250,
                'numTeacher' => 20,
                'movie' => 'https://youtube.com/dummy3',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SMAN 1 Mengwi',
                'institutionCode' => 'INST0004',
                'schoolId' => 4,
                'statusId' => 2,
                'educationLevelId' => 3,
                'ownershipStatus' => 'Swasta',
                'dateEstablishmentDecree' => '2010-01-01',
                'operationalLicense' => 'IZIN-004',
                'dateOperationalLicense' => '2011-01-01',
                'principal' => 'Ni Ketut Rahayu',
                'operator' => 'Gusti Made',
                'accreditationId' => 2,
                'curriculum' => 'Kurikulum Merdeka',
                // 'telpNo' => '0361-123004',
                'tuitionFee' => 200000,
                'numStudent' => 500,
                'numTeacher' => 40,
                'movie' => 'https://youtube.com/dummy4',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SDN 4 Denpasar Barat',
                'institutionCode' => 'INST0005',
                'schoolId' => 5,
                'statusId' => 1,
                'educationLevelId' => 1,
                'ownershipStatus' => 'Negeri',
                'dateEstablishmentDecree' => '2007-01-01',
                'operationalLicense' => 'IZIN-005',
                'dateOperationalLicense' => '2008-01-01',
                'principal' => 'Putu Arini',
                'operator' => 'Agus Dharma',
                'accreditationId' => 1,
                'curriculum' => 'K13',
                // 'telpNo' => '0361-123005',
                'tuitionFee' => 0,
                'numStudent' => 280,
                'numTeacher' => 22,
                'movie' => 'https://youtube.com/dummy5',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SMPN 1 Denpasar Barat',
                'institutionCode' => 'INST0006',
                'schoolId' => 6,
                'statusId' => 2,
                'educationLevelId' => 2,
                'ownershipStatus' => 'Swasta',
                'dateEstablishmentDecree' => '2006-01-01',
                'operationalLicense' => 'IZIN-006',
                'dateOperationalLicense' => '2007-01-01',
                'principal' => 'I Nyoman Suta',
                'operator' => 'Komang Rika',
                'accreditationId' => 2,
                'curriculum' => 'Kurikulum Merdeka',
                // 'telpNo' => '0361-123006',
                'tuitionFee' => 180000,
                'numStudent' => 350,
                'numTeacher' => 28,
                'movie' => 'https://youtube.com/dummy6',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SMAN 2 Denpasar Timur',
                'institutionCode' => 'INST0007',
                'schoolId' => 7,
                'statusId' => 1,
                'educationLevelId' => 3,
                'ownershipStatus' => 'Negeri',
                'dateEstablishmentDecree' => '2012-01-01',
                'operationalLicense' => 'IZIN-007',
                'dateOperationalLicense' => '2013-01-01',
                'principal' => 'Ni Luh Intan',
                'operator' => 'Made Budi',
                'accreditationId' => 1,
                'curriculum' => 'K13',
                // 'telpNo' => '0361-123007',
                'tuitionFee' => 0,
                'numStudent' => 520,
                'numTeacher' => 38,
                'movie' => 'https://youtube.com/dummy7',
                'examInfo' => 'UNBK',
            ],
            [
                'name' => 'SMKN 1 Denpasar Timur',
                'institutionCode' => 'INST0008',
                'schoolId' => 8,
                'statusId' => 2,
                'educationLevelId' => 4,
                'ownershipStatus' => 'Swasta',
                'dateEstablishmentDecree' => '2015-01-01',
                'operationalLicense' => 'IZIN-008',
                'dateOperationalLicense' => '2016-01-01',
                'principal' => 'Wayan Putri',
                'operator' => 'Gede Surya',
                'accreditationId' => 2,
                'curriculum' => 'Kurikulum Merdeka',
                // 'telpNo' => '0361-123008',
                'tuitionFee' => 250000,
                'numStudent' => 480,
                'numTeacher' => 36,
                'movie' => 'https://youtube.com/dummy8',
                'examInfo' => 'UNBK',
            ],
        ]);
    }
}
